language: node_js
node_js:
- 6
- node
dist: trusty
sudo: required
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=production
before_install:
  - wget ftp://crispeditor.co.uk/pub/release/website/dtrace/dtrace-20160613.tar.bz2
  - bunzip2 < dtrace-20160613.tar.bz2 | tar xvf -
install:
  - npm --production=false install
  - npm --production=false update
  - cd dtrace-20160613
  - sudo tools/get-deps.pl
  - make all
  - sudo make install
  - sudo make load
  - cd ..
before_script:
- chmod a+x travis-after-success-bench.sh
after_script:
- |
  # RELEASE_BRANCHES and NPM_TOKEN defined in Travis settings panel
  declare exitCode
  $(npm bin)/travis-after-all
  exitCode=$?
  if [[
    # Execute after all jobs finish successfully
    $exitCode = 0 &&
    # Only release on release branches
    $RELEASE_BRANCHES =~ $TRAVIS_BRANCH &&
    # Don't release on PR builds
    $TRAVIS_PULL_REQUEST = "false"
  ]]; then
    # Authenticate NPM
    echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    # Set version to timestamp
    npm --no-git-tag-version version $($(npm bin)/json -f package.json version)-prerelease.$(date +%s)
    npm publish
    # Publish to gh-pages as most recent committer
    git config --global user.email $(git log --pretty=format:"%ae" -n1)
    git config --global user.name $(git log --pretty=format:"%an" -n1)
    npm run --silent deploy -- -x -r $GH_PAGES_REPO
  fi
after_success:
  - sudo dtrace -V
  - sudo dtrace -c ./node_modules/.bin/tap ./test/integration/performance_test.js > out2.txt
  - cat out2.txt
  - ./travis-after-success-bench.sh